---
title: "data import muddiest"
author: "LUIZA DIVINO"
date: "2024-10-07"
output: github_document
---

# Linguistic Description of Characters in Machado de Assis’ Dom Casmurro

## Brief summary
I would like my project to be an intersection between Corpus Linguistics and Literature. To do so, I will focuses on *Dom Casmurro* by Machado de Assis (1839-1908), a Brazilian author. The story is written in first person by the main character called Bentinho, who induces the readers to believe that his wife called Capitu had an affair with one of his best friends called Escobar.

The goal is to verify how Capitu and Escobar are described throughout the story, making a comparison between how they were portrayed by Bentinho before and after the apparent adultery.

## Data
For my analysis I will be using the whole book as a corpus, which can be downloaded in PDF format using this link <https://machado.mec.gov.br/obra-completa-lista/itemlist/category/23-romance>. Since the book is already in PDF format, there is no need to transform the data into another format.

## Analysis 
First, I would like to know how many times each name occured in the story comparing to other words that had also occured many times. My guess is that Bentinho was so obsessed with the idea of them both having an affair that both of their names (Capitu and Escobar) occur more than other content words, especially Capitu’s name. In this first part, I would like to extract simple frequency lists and compare them to other content words.

After that, I would like to access words that co-occur with those two names. The words don’t have to be necessarily side by side, but in a
range that I will have to choose based on initial testing. My hypothesis is that it may be possible to track linguistic changes in the beginning and in the end of the story, not only in terms of vocabulary but also structure used to describe both characters. Bentinho narrates what all the characters say and do, so it may be possible to recognize differences in verbs and also adjectives used. It is also important to understand what this changes could mean according to the story.

I would like to see some of the results (words that co-ocurr) in the form of word clouds when presenting which words co-occur with both names. As for the other parts of the analysis, I still have to figure out what is the best way to demonstrate them.

## R Packages needed
For this project, I will be working with the following packages: `pdftools`, `tibble`, `tidytext`, `tidiverse`, `dyplr` and `stringr`.

## Early Resources
Viana, V., Fausto, F., & Zyngier, S. (2007). Corpus linguistics & literature: A contrastive analysis of Dan Brown and Machado de Assis. In S. Zyngier, V. Viana, & J. Jandre (Eds.), Textos e leituras: Estudos empíricos de língua e literatura (pp. 233-256). Publit.


